version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: mha
      MYSQL_PASSWORD: mh@4mysql
  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
