version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: mha
      MYSQL_PASSWORD: mh@4mysql
    volumes:
      - ./create_replication.sh:/docker-entrypoint-initdb.d/create_replication.sh:ro
  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
